### PR TITLE
Create vi.lang

### PR DESCRIPTION
**Pull request by thuan244**
Create Vietnamese translation file

### CODE REVIEW

**Comment by cizia64** [comment]
Hi, can you also create a vi.lang.short file please ?
It contains the labels used in Retroarch in game menu.

The content looks like that: 

```
{
	"46":	"OK",	
	"88":	"OPEN",
	"89":	"BACK",
	"90":	"NAV",
	"91":	"MENU",
	"92":	"Continue",
	"93":	"Save",
	"94":	"Load",
	"95":	"Volume",
	"96":	"Exit Game",
	"97":	"Record %d/%d",
	"98":	"Empty",
	"99":	"No Thumb",
	"100":	"load fail",
	"101":	"save fail",
	"102":	"slot%d saved",
	"103":  "Fullscreen",
	"104":  "On",
	"105":  "Off",
	"118":  "Netplay",
	"126":  "Advanced Menu"
}
```

**Comment by thuan244** [comment]
Hi, I created a vi.lang.short file as well, please review it and let me know. Thanks.

**Comment by cizia64** [comment]
A little flag [like this one](https://github.com/thuan244/CrossMix-OS/blob/main/trimui/res/lang/lang_pl.png) and it will be perfect, resolution : 530px × 90px

**Comment by thuan244** [comment]
Hi, I've added lang_vi.png image, please have a look and let me know, thanks.

**Comment by cizia64** [comment]
That's perfect, thank you.

**Pull request merged**
