### PR TITLE
Add launch options for multiple arcade emulators

### PR DESCRIPTION
**Pull request by cobaltgit**
This pull request adds the option to launch CP System I/II/III and PGM games using the libretro FB Neo core, as well as launch options for Neo Geo.

### CODE REVIEW

**Comment by cobaltgit** [comment]
Maybe default to fbneo launch?

**Comment by cobaltgit** [comment]
Geolith core launch option added. Note that this only works with TerraOnion `.neo` format ROMs.

**Comment by cizia64** [comment]
We have a problem due to this : https://github.com/cizia64/CrossMix-OS/blob/c8f6f2c6b93efab76a2bd6ff4f4faaf3367edbd9/Apps/SystemTools/Menu/THEME%23%23ICONS%20(value)/Default.sh#L15
The icon switcher will set an image which doesn't exist.

We could create a copy of NEOGEO icon for each icon pack :grimacing: ... 
But may be I haven't proposed the best solution : why do you think about a a launch script which picks the right GEOLITH core when the rom extension is .geo ? 
Like that we don't have a new emu folder and the user can put neogeo roms in this folder whatever the format.

**Comment by cobaltgit** [comment]
Oh right I'll have to create a copy of the NeoGeo icon for Geolith, I'll get to that

**Pull request merged**
