### PR TITLE
[Various] Disable threaded video for GB,GBC,NES,SNES emulators

### PR DESCRIPTION
**Pull request by cobaltgit**
This pull request disables threaded video specifically for Gameboy, Gameboy Color, NES and SNES emulators specifically as referred to in #31

### CODE REVIEW

**Comment by cobaltgit** [comment]
This one will require quite a bit of testing...

**Comment by xsilas43** [comment]
Disabling threaded video for SNES9x causes the fps to drop from 60 to 55 and remain there consistently in the romhack "A Plumber For All Seasons". Might be a bit more taxing than the average SNES game.

**Comment by luizluan** [comment]
> Disabling threaded video for SNES9x causes the fps to drop from 60 to 55 and remain there consistently in the romhack "A Plumber For All Seasons". Might be a bit more taxing than the average SNES game.

Maybe something to do with the SA-1 chip emulation. My problem with threaded video was only with Gameboy. And they reported to me that the nes has the same problem.

**Comment by luizluan** [comment]
I don't know what changed in the last version but I haven't had problems with frames since the last version.

**Comment by cizia64** [comment]
> I don't know what changed in the last version but I haven't had problems with frames since the last version.

The slowdown was due to ALSA audio output, switching to OSS and no more stuttering...except that OSS is not working with bluetooth, so I've made a trick to automatically switch to ALSA again when a bluetooth device is connected (which means indeed less good performances when a bluetooth device is connected but for now we have no other choice). 

https://github.com/cizia64/CrossMix-OS/commit/b1f7ccb5762925f266f4f7a983acf328351e7d1e

So I close this PR ;)

**Pull request closed without merging**
