### PR TITLE
[Emus] Add stella2014 launcher

### PR DESCRIPTION
**Pull request by Nevrdid**
Added the launcher and and place it in first launchlist position ( default )

### CODE REVIEW

**Comment by cizia64** [comment]
Is there any savestate compatibility between both cores ? May be we don't car about atari savestates as game sessions are generally not very long ?

**Comment by Nevrdid** [comment]
> Is there any savestate compatibility between both cores ? May be we don't car about atari savestates as game sessions are generally not very long ?

Alright, just tried and saves are not compatible. However, as select anyway act as a kindof reset ( not really but i don't understood is exact purpose), we can't barely save anyway. And about the mainUI menu saves, as they are not the same core, they don't appear as savestates when we switch the core.

**Comment by schmurtzm** [comment]
The original Stella is totally already running at full speed but it's true that it uses more cpu than expected for a low demanding system.
Indeed I can clearly see that stella 2014 is a lot less demanding. 
I wonder why Batocera favors stella over stella2014 including on slow boards (only RPi 1 will use the version 2014)... a question about emulation accuracy ?
However Onion is using the version 2014, which is a good sign, so let's merge this ;)

**Comment by cizia64** [comment]
I can clearly see that stella2014 is less demanding (even if the main stella is running at full speed on the TSP on every games).
I wonder why Batocera favors stella over stella2014 (only RPi 1 will use the version 2014)... a question about accuracy ?
However Onion is using stella 2014, which is a good sign.
So let's merge this !

**Pull request merged**
