### PR TITLE
Add Tailscale

### PR DESCRIPTION
**Pull request by cgimenes**

### CODE REVIEW

**Comment by cizia64** [comment]
Great, thank you for this PR ! 
Now I have to learn to use TailScale (I use Wireguard and OpenVPN everyday but not this one). Fortunately they seem to have a [great documentation](https://tailscale.com/kb/1278/tailscaled).
Can you detail which sources have been built and the common use you'll have with it ?

**Comment by cgimenes** [comment]
> Great, thank you for this PR ! 
> Now I have to learn to use TailScale (I use Wireguard and OpenVPN everyday but not this one). Fortunately they seem to have a [great documentation](https://tailscale.com/kb/1278/tailscaled).
> Can you detail which sources have been built and the common use you'll have with it ?

You just need to run `tailscale up` once, and it'll work.

What do you mean by sources? Are you talking about the binaries? If so, I just downloaded them for the aarm64 arch.

I use Tailscale together with Syncthing to keep a VM running in a cloud provider without exposing it to the Internet. The VM is there to keep my RG35XX H and my TSP synced without having to turn both on at the same time.

**Comment by cizia64** [comment]
Thanks, yes I was talking about the origin of the binaries 👍
That an interesting use indeed. Speaking about that, one day it would be nice to write an article in the wiki to explain how to setup the saves & save states sync between two devices. 
The VPN can also be potentially interesting for multiplayer under certain circumstances...

I'll test that and merge it soon ;)

**Comment by ashes00** [comment]
Tailscale on Crosmix OS would be out of this world awesome! TY!

**Pull request merged**
